/**
 * List of available anime genres.
 *
 * @see {@link https://github.com/jikan-me/jikan/blob/master/src/Helper/Constants.php}
 */
export enum JikanApiAnimeGenre {
    GENRE_ACTION = 1,
    GENRE_ADVENTURE = 2,
    GENRE_CARS = 3,
    GENRE_COMEDY = 4,
    GENRE_DEMENTIA = 5,
    GENRE_DEMONS = 6,
    GENRE_MYSTERY = 7,
    GENRE_DRAMA = 8,
    GENRE_ECCHI = 9,
    GENRE_FANTASY = 10,
    GENRE_GAME = 11,
    GENRE_HENTAI = 12,
    GENRE_HISTORICAL = 13,
    GENRE_HORROR = 14,
    GENRE_KIDS = 15,
    GENRE_MAGIC = 16,
    GENRE_MARTIAL_ARTS = 17,
    GENRE_MECHA = 18,
    GENRE_MUSIC = 19,
    GENRE_PARODY = 20,
    GENRE_SAMURAI = 21,
    GENRE_ROMANCE = 22,
    GENRE_SCHOOL = 23,
    GENRE_SCI_FI = 24,
    GENRE_SHOUJO = 25,
    GENRE_SHOUJO_AI = 26,
    GENRE_SHOUNEN = 27,
    GENRE_SHOUNEN_AI = 28,
    GENRE_SPACE = 29,
    GENRE_SPORTS = 30,
    GENRE_SUPER_POWER = 31,
    GENRE_VAMPIRE = 32,
    GENRE_YAOI = 33,
    GENRE_YURI = 34,
    GENRE_HAREM = 35,
    GENRE_SLICE_OF_LIFE = 36,
    GENRE_SUPERNATURAL = 37,
    GENRE_MILITARY = 38,
    GENRE_POLICE = 39,
    GENRE_PSYCHOLOGICAL = 40,
    GENRE_THRILLER = 41,
    GENRE_SEINEN = 42,
    GENRE_JOSEI = 43,
}
